### ISSUE TITLE
New travis failures for 3.5.1 (dalehhenrich/Grease)

### ISSUE THREAD

**Issue by dalehenrich** [SeasideSt/Grease#105]
In [this travis build](https://travis-ci.org/github/GsDevKit/Grease/jobs/696955030#L2741), 3.5.0 tests are failing. [We are getting an ObjectSecurityError](https://travis-ci.org/github/GsDevKit/Grease/jobs/696955030#L2130) and that is odd because a month ago, the [travis tests passed](https://travis-ci.org/github/GsDevKit/Grease/jobs/685385434)
the 3.5.0 release hasn't changed for three years ... so something else in the build pipeline has changed in the last month ...

**Comment by jbrichau** [comment]
@dalehenrich Ow, I did not get pinged you actually sent this one in to me. I pinged you if you know about this (https://github.com/SeasideSt/Seaside/issues/1198#issuecomment-650553034)

The build worked fine on May 23d, when I made the last change to Grease in this repo: https://travis-ci.org/github/SeasideSt/Grease/builds/690310159 and it started failing from then.

So, afaik, there is nothing in Grease itself that made this fail.

**Comment by dalehenrich** [comment]
AFAIK, nothing changed on that magical day ... but something did and I hope I can find it ... it also seems that the failures do not occur when run locally out of local git clones ... I have more work to do to just reproduce the problem it seems ... hopefully, it isn't just travis where the problems reproduce:)

**Comment by dalehenrich** [comment]
I have isolated the failures to be related to the use of SmalltalkCI and an updateMetacello call within the SmalltalkCI framework (https://travis-ci.org/github/GsDevKit/Grease/jobs/702843448#L2003-L2080):
```
ERROR 2116 , a SecurityError occurred (error 2116), An attempt was made to modify the object aGsMethodDictionary in objectSecurityPolicyId 1 with insufficient authorization. (SecurityError)

topaz > exec iferr 1 : stk 

==> 1 SecurityError (AbstractException) >> _signalFromPrimitive: @5 line 15

2 GsMethodDictionary >> _atKey:put:             @1 line 9

3 GsMethodDictionary >> removeKey:ifAbsent:     @7 line 11

4 GsMethodDictionary (AbstractDictionary) >> removeKey: @2 line 8

5 Collection class (Behavior) >> _basicRemoveSelector:environmentId: @11 line 10

6 Collection class (Behavior) >> removeSelector:environmentId: @8 line 12

7 Collection class (Behavior) >> removeSelector:environmentId:ifAbsent: @13 line 15

8 Collection class (Behavior) >> removeSelector:ifAbsent: @2 line 2

9 [] in MCMethodDefinition >> unload            @13 line 5

10 Collection class (Object) >> ifNotNilDo:      @2 line 4

11 MCMethodDefinition >> unload                  @8 line 5

12 [] in MCPackageLoader >> basicLoad            @48 line 11

13 OrderedCollection (Collection) >> do:         @5 line 10

14 OrderedCollection (Collection) >> do:displayingProgress: @2 line 3

15 [] in MCPackageLoader >> basicLoad            @20 line 11

16 ExecBlock0 (ExecBlock) >> on:do:              @3 line 44

17 [] in MCPackageLoader >> basicLoad            @15 line 49

18 ExecBlock0 (ExecBlock) >> ensure:             @2 line 12

19 MCPackageLoader >> basicLoad                  @11 line 51

20 [] in MCPackageLoader >> loadWithNameLike:    @12 line 4

21 [] in MCPackageLoader >> useChangeSetNamed:during: @13 line 9

22 ExecBlock0 (ExecBlock) >> ensure:             @2 line 12

23 MCPackageLoader >> useChangeSetNamed:during:  @9 line 9

24 MCPackageLoader >> useNewChangeSetNamedLike:during: @3 line 2

25 MCPackageLoader >> loadWithNameLike:          @6 line 4

26 MCVersionLoader >> load                       @9 line 6

27 MetacelloGoferLoad (GoferLoad) >> execute     @6 line 3

28 [] in MetacelloCommonMCSpecLoader >> loadPackageDirective:gofer: @46 line 17

29 [] in MetacelloCommonMCSpecLoader >> loadPackageDirective:gofer: @23 line 21

30 MetacelloGemStonePlatform (MetacelloPlatform) >> do:displaying: @2 line 3

31 MetacelloLoadingMCSpecLoader (MetacelloCommonMCSpecLoader) >> loadPackageDirective:gofer: @7 line 5

32 MetacelloLinearLoadDirective (MetacelloVersionLoadDirective) >> loadPackageDirective:gofer: @4 line 4

33 MetacelloPackageLoadDirective >> loadUsing:gofer: @2 line 3

34 [] in MetacelloVersionLoadDirective >> loadLinearLoadDirective:gofer: @8 line 3

35 OrderedCollection (Collection) >> do:         @5 line 10

36 MetacelloLinearLoadDirective (MetacelloVersionLoadDirective) >> loadLinearLoadDirective:gofer: @3 line 3

37 MetacelloLinearLoadDirective >> loadUsing:gofer: @6 line 4

38 [] in MetacelloVersionLoadDirective >> loadLinearLoadDirective:gofer: @8 line 3

39 OrderedCollection (Collection) >> do:         @5 line 10

40 MetacelloLinearLoadDirective (MetacelloVersionLoadDirective) >> loadLinearLoadDirective:gofer: @3 line 3

41 MetacelloLinearLoadDirective >> loadUsing:gofer: @6 line 4

42 MetacelloLinearLoadDirective (MetacelloVersionLoadDirective) >> loadWithPolicy: @7 line 7

43 MetacelloLoaderPolicy >> load                 @6 line 4

44 MetacelloFetchingMCSpecLoader >> doLoad       @4 line 3

45 [] in MetacelloMCVersion >> doLoadRequiredFromArray: @40 line 12

46 MetacelloGemStonePlatform (MetacelloPlatform) >> do:displaying: @2 line 3

47 [] in MetacelloMCVersion >> doLoadRequiredFromArray: @31 line 12

48 ExecBlock0 (ExecBlock) >> ensure:             @2 line 12

49 MetacelloMCVersion >> doLoadRequiredFromArray: @22 line 16

50 Array (Collection) >> loadRequiredForMetacelloMCVersion: @2 line 3

51 MetacelloMCVersion >> load:                   @2 line 3

52 [] in MetacelloScriptEngine >> load:onProjectDownGrade:onProjectUpgrade: @18 line 16

53 ExecBlock0 (ExecBlock) >> on:do:              @3 line 44

54 [] in MetacelloScriptEngine >> handleNotificationsForAction: @20 line 6

55 ExecBlock0 (ExecBlock) >> on:do:              @3 line 44

56 [] in MetacelloScriptEngine >> handleNotificationsForAction: @12 line 14

57 ExecBlock0 (ExecBlock) >> on:do:              @3 line 44

58 [] in MetacelloScriptEngine >> handleNotificationsForAction: @6 line 20

59 ExecBlock0 (ExecBlock) >> on:do:              @3 line 44

60 MetacelloScriptEngine >> handleNotificationsForAction: @2 line 24

61 [] in MetacelloScriptEngine >> load:onProjectDownGrade:onProjectUpgrade: @6 line 5

62 ExecBlock0 (ExecBlock) >> ensure:             @2 line 12

63 MetacelloProjectRegistration class >> copyRegistryRestoreOnErrorWhile: @8 line 14

64 MetacelloScriptEngine >> load:onProjectDownGrade:onProjectUpgrade: @2 line 3

65 MetacelloScriptEngine >> load:                @2 line 3

66 MetacelloScriptEngine (Object) >> perform:withArguments: @1 line 12

67 [] in MetacelloScriptExecutor >> execute:     @40 line 15

68 [] in MetacelloScriptApiExecutor >> executeString:do: @13 line 6

69 Array (Collection) >> do:                     @5 line 10

70 MetacelloScriptApiExecutor >> executeString:do: @6 line 4

71 String >> execute:against:                    @2 line 2

72 MetacelloScriptApiExecutor (MetacelloScriptExecutor) >> execute: @6 line 9

73 Metacello >> execute:args:                    @8 line 5

74 Metacello >> load:                            @2 line 2

75 SCIGemStoneMetacelloLoadSpec class (SCIMetacelloLoadSpec class) >> updateMetacello @11 line 9
```

**Comment by dalehenrich** [comment]
@jbrichau, it looks like the problem is that while `useLatestMetacello` has been set to true in the [Grease .smalltalk.ston file](https://github.com/GsDevKit/Grease/blob/master/.smalltalk.ston#L7) for quite some time, [a GemStone-only bug introduced recently in Metacello](https://github.com/Metacello/metacello/issues/518) ... And the Metacello bug was masked by the fact that there were some expected test failures that masked the fact that the builds were failing for 3.5.x ...

This particular bug is strictly a SmalltalkCI issue, since in normal circumstances a GLASS installation will not be loading Metacello from Metacello/metacello. And I'm thinking of [partly addressing the bug by ignoring `useLatestMetacello`](https://github.com/hpi-swa/smalltalkCI/issues/459#issuecomment-651440961). What do you think ... 

Unlike the Pharo and Squeak images, it is possible that the latest version of Metacello has to be explicitly loaded, but GLASS builds always use the latest Metacello when building the stone ... so this shouldn't really be a problem for GemStone ...

I've run out of time to do any more work tonight, but depending upon your thoughts I'll go about arranging that `useLatesMetacello` will be ignored by GemStone ... and while I'm at it, I will look into fixing the JSON tests (that cause us to ignored the introduced Metacello bug (Metacello/metacello#518)

**Comment by jbrichau** [comment]
@dalehenrich Great catch. I was staring at the difference between the SeasideSt/Parasol builds (which work) and the SeasideSt/Grease builds that fail (and indeed, only on TravisCI) and just did not discern that difference. I have removed the setting for the GemStone builds both in Grease and Seaside. The builds are green: https://travis-ci.org/github/SeasideSt/Seaside/builds/703421248 and https://travis-ci.org/github/SeasideSt/Grease/builds/703425342 

About ignoring the setting: I guess it would be better to throw an error and make people remove the setting for Gemstone builds. Silent ignores can be a mindf**k ;-)

**Comment by dalehenrich** [comment]
@jbrichau, I understand that  silently ignoring can be a problem, but I _am_ concerned about the possible cases where the useLatestMetacello is needed for pharo/squeak and at the moment there is no way to make that setting conditional. At the end of the day, the issue was the fact that Metacello/metacello got released with a fatal error for GemStone 3.5.x (Metacello/metacello#518) .. so for now I will hold off changing smalltalkCI until I hear from you again and work on getting the Metacello/metacello builds passing:)

**Comment by jbrichau** [comment]
Hey @dalehenrich, I only removed the ‘useLatestMetacello’ for Gemstone builds. So, that is possible. Yes, people will have to fix their smalltalk.ston files because of a change in SmalltalkCI then. But it will be easy to see and fix a “useLatestMetacello not supported in Gemstone builds” error popping up.

I’m game either way you choose since there is always a trade-off to make and both paths have a good solution.

**Comment by dalehenrich** [comment]
Ultimately, it is more of a performance issue modulo Metacello bugs, since a reload of Metacello should be totally unnecessary in GemStone, but probably should go work anyway ... in the (hopefully) short term, now that we understand the issue, I'm not interested n spending anymore time on the SmalltalkCI work and spend my limited time window addressing Metacello issues:)

Thanks for the discussion and flexibility:)
