### ISSUE TITLE
#= not defined for GRSmallDictionary

### ISSUE THREAD

**Issue by jbrichau** [SeasideSt/Grease#11]
(original issue disappeared because old Grease repo was removed)

@dalehenrich was wondering why comparison was not defined on GRSmallDictionary while he is working on porting STON to GemStone. Instead of porting SmallDictionary, he wants to use GRSmallDictionary. However, this requires a comparison to be defined on that class.

**Comment by jbrichau** [comment]
Response of @marschall to the original issue:

```
After some discussion with @jbrichau there doesn't seem to be an easy fix:

Pharo does support #= for Collections so we would have to have a #= and #hash implementation that is specific for Pharo.
Pharo does #= based on #isDictionary. Therefore GRSmallDictionary can compare true to Dictionary in Pharo.
GemStone/S does #= based on #_class. Therefore GRSmallDictionary can not compare true to Dictionary in GemStone/S so
    GRSmallDictionary new = Dictionary new
would be true in Pharo but false in GemStone/S.

VW does not support #= for Collections so
    GRSmallDictionary new = Dictionary new
would be true in Pharo but false in VW.

Therefore it's hard to get consistent semantics across platforms.
```

**Comment by dalehenrich** [comment]
That's good enough for me ... It is not imperative that I replace SmallDictionary with GRSmallDictionary in STON for GemStone ... thanks for the effort

**Comment by dalehenrich** [comment]
BTW, @jbrichau could you make me a member of the SeasideST organization ... I noticed that I cannot close the issue myself:) and it would be convenient ... but there's no hurry if you are still in the process of getting things organized ...

**Comment by jbrichau** [comment]
Invitation sent!

Johan (sent from my mobile)

**Comment by dalehenrich** [comment]
thx
