### ISSUE TITLE
GRNumberPrinter produces wrong decimal output

### ISSUE THREAD

**Issue by eMaringolo** [SeasideSt/Grease#110]
`GRNumberPrinter new precision: 1; accuracy: 0.1; print: 25.97` produces `'25.10'`.

This is wrong in that it produces an output with more precision than the specified, and with a decimal part that is different than it's rounded/truncated value.

It is not clear to me whether this should be `25.9` or `26.0`.

**Comment by theseion** [comment]
I would expect  `25.9` because you set accuracy to `0.1`. I expect that an accuracy of `0.01` will produce `26.0`. In any case, the precision seems to be wrong, I agree.

**Comment by eMaringolo** [comment]
As for my use case I'd expect a rounding effect, e.g.

25.97 -> "26.0"
25.95 -> "26.0"
25.94 -> "25.9"
25.949 -> "25.9"
25.15 -> "25.2"

Basically anything greater or equal than 5 is rounded up, while everything else is rounded down.
This would require processing the fraction part before the integer part though.

**Comment by jbrichau** [comment]
Which platform did you test this on and which version of Grease?

I tried in Pharo8 and 9:
`GRNumberPrinter new precision: 1; accuracy: 0.1; print: 25.97` -> `26.0`
`GRNumberPrinter new precision: 1; accuracy: 0.1; print: 25.15` -> `25.1`

Of course, it just prints a number and does not round according to the rounding rules. There is no rounding done in the printer.

**Comment by eMaringolo** [comment]
I had a conflict when loading Grease, one project depended on the HEAD commit in the `master` branch, while all the rest depended on the `v1.6.x` tag, but on conflict I used the incoming one, that was not the one in the tagged branch.

Bottom line: I was using an older version of Grease. This can be closed, in the commit of the 1.6.x tag it works as expected.
