### ISSUE TITLE
GsDevKit/Grease port to 3.5.6

### ISSUE THREAD

**Issue by dalehenrich** [SeasideSt/Grease#116]
baseline specifies some 3.5.5 packages, but 3.5.6 needs to be on the list

**Comment by dalehenrich** [comment]
fixed by [this commit](https://github.com/GsDevKit/Grease/commit/8762b69159d39177215f051c5a2f7483e43d2c6f)

**Comment by jbrichau** [comment]
@dalehenrich I think it's a good idea to make sure we have the necessary changes in this repo as well. This will avoid merge problems in the future.

**Comment by dalehenrich** [comment]
@jbrichau makes sense ...

**Comment by dalehenrich** [comment]
@jbrichau [one build failed with an odd error](https://github.com/SeasideSt/Grease/runs/2299486525?check_suite_focus=true#step:4:1360) ... especially odd, because on line 1345 the netldi was successfully started ... and even odder, because the [travis build succeeded](https://travis-ci.org/github/SeasideSt/Grease/builds/766375599) ... travis seems to not allow rebuild of a failed run anymore --- are they copying github behavior or ??? ... oh well, it's a free service, so I can't complain can I :)

I will go ahead a create a PR for this and you can let me know if you want anything else done ...

**Comment by jbrichau** [comment]
@dalehenrich thanks!
