### ISSUE TITLE
Can we remove GRUtf8CodecTest>>expectedFailures ?

### ISSUE THREAD

**Issue by marianopeck** [SeasideSt/Grease#119]
Hi guys, 

```smalltalk 
GRUtf8CodecTest>>expectedFailures
^  SystemVersion current major < 9 
		ifTrue: [ #(testCodecUtf8ShortestForm) ]
		ifFalse:[ #() ]
```

Makes my VAST port more complicated because VAST does not have `SystemVersion` class. I would be happy to include if at least it would be part of Grease itself..but right now that doesn't seem to be the case and its just to mark a failing test before < 9. Even more... this is coupled to Pharo but on a generic package.. I guess Squeak and GemStone even if they may have `SystemVersion`, they sure have different numbers.

Thoughts?

**Comment by jbrichau** [comment]
@marianopeck hm... you raise an interesting point that this code should not even work on GemStone but it's not causing a failed build at the moment...

It should be part of the Pharo-specific package. I will move it but first I want to find out why this build is not failing..

**Comment by marianopeck** [comment]
Hi Johan,

Maybe because GemStone overrides that method: https://github.com/SeasideSt/Grease/blob/master/repository/Grease-Tests-GemStone-Core.package/GRUtf8CodecTest.extension/instance/expectedFailures.st

**Comment by jbrichau** [comment]
@marianopeck haha, that's a good point :-)
I did not look at it yet, but that's the obvious difference. There should be a supercall there... 

I will only be able to change it later this week, but you can assume the method is Pharo specific.

**Comment by marianopeck** [comment]
Excellent! I am not on a rush and thanks for taking care, that is much appreciated.

**Comment by marianopeck** [comment]
Thanks Johan!
