### ISSUE TITLE
Grease GitHub Baseline Repository for 1.5.x not locked.  prevents Metacello load of later version (1.7)

### ISSUE THREAD

**Issue by Robert-Briggs** [SeasideSt/Grease#124]
I get a  Metacello load conflict in Pharo 9 when I try to load the latest Seaside which requires Grease 1.7, because I have 1.5.x loaded.  Same thing happens when I try and load latest version of Grease on its own.

It appears that the test:
self existingProjectRegistration locked
 returns false.
This causing the default action 'useIncoming' to be bypassed and raising MetacelloConflictingProjectError.

Please advise.

**Comment by jbrichau** [comment]
This is not a Grease issue and the same issue was discussed in https://github.com/SeasideSt/Seaside/issues/1276
