### ISSUE TITLE
Redo Pharo packages

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Grease#14]
The current Pharo packages are done so that code duplication is minimised but the result is very confusing. Eg. `Grease-Pharo30-Core` and `Grease-Pharo40-Core` are both loaded into a Pharo 5 image.

I wonder if it would be better to just copy and paste the packages for every dialect version.

**Comment by dalehenrich** [comment]
Yeah I think it makes sense to consolidate the changes ... redundancy is only a problem if it becomes necessary to change the same method in all copies ... but for these packages that will never be the case ...

**Comment by jbrichau** [comment]
Same thought for the Gemstone package. I agree. It becomes impossible to understand. Fixes will have to be duplicated but that's easy to understand.

I could still do this for the Pharo6 package as it's only a pre-release, so I probably will.

**Comment by marschall** [comment]
Looking at the current Baseline https://github.com/SeasideSt/Grease/blob/dev/repository/BaselineOfGrease.package/BaselineOfGrease.class/instance/baseline..st this seems to be done.

**Comment by jbrichau** [comment]
For Pharo6 this was done but the original remark of the packages for Pharo3 and Pharo4 still holds. Then again, I don't think we should fix it for the older platforms as they will fade out anyway.

**Comment by marschall** [comment]
The way I interpret the baseline is that for Pharo3, Pharo4 and Pharo5 we *only* load `Grease-Pharo30-Core`. Which is not ideal but much butter and loading `Grease-Pharo30-Core` and `Grease-Pharo40-Core` which was the confusing part this issue is about.

**Comment by jbrichau** [comment]
Ok, but I don't think this was ever the case, actually. (see https://github.com/SeasideSt/Grease/commits/dev/repository/BaselineOfGrease.package/BaselineOfGrease.class/instance/baseline..st)

**Comment by marschall** [comment]
I consider this done.
