### ISSUE TITLE
GRGemStonePlatform>>seasideGettextExampleFilesDirectory results in error if GS_HOME isn't defined, however ....

### ISSUE THREAD

**Issue by dalehenrich** [SeasideSt/Grease#146]
... this prevents users running GemStone Grease tests from getting clean test runs when GS_HOME is not defined, so an error is harsh ... there might be other ways to determine where the Seaside project is ... but they are also probably iffy as well ... 

In my partjucular use case, I'm using Metacello to load the project into my image, but I'm not using GS_HOME ... As it happens, it looks like the following expression would work if Metacello is present (a pretty good bet) to get the repository url used to load Seaside:
``` smalltalk
| projectSpec |
  (projectSpec := (Metacello image
    project: 'Seaside3';
    list) detect: [ :each | true ] ifNone: [ self halt ]) repositories list
    first name
```
and this would probably work for a github: url as well ...

Personally I'd think that skipping the test itself if GS_HOME isn't present would be okay ... we test Seaside against our internal builds using both GS_HOME and Metacello, 

I also suppose there are alternate ways to create the translator from embedded methods?

It looks like trying to skip the tests is complicated as well, because currently the calls are made from the setUp method and that is in common code ...

I'll assign this to @jbrichau and if you have an approach that you want to take let me know if I can help

**Comment by jbrichau** [comment]
Hi @dalehenrich,

Darn. I was hoping your internal tests were using the GsDevKit_HOME. :-)
I guess I should have gone with files loaded into methods like it's done in other tests.... 
No problem. I'll fix that asap.

**Comment by dalehenrich** [comment]
Sounds good ... this isn't an emergency, since release is months away ... so feel free to strike when you iron is hot :) THANKS..

**Comment by dalehenrich** [comment]
We are targeting end of year for our release (not a hard target), so getting this off of our plate in the next month would be good ... if you've decided on a the approach, but don't have the time, let me know and I'll take a crack at it ...

**Comment by jbrichau** [comment]
oeps, fell off my radar at some point. I think I decided on moving the files to methods and generating them in a temporary file location. Should be easy enough to get done but I'm heads down this week on other things. The timeframe of 'in the next month' should be fine ;-)

**Comment by jbrichau** [comment]
@dalehenrich This should now be fixed: https://github.com/SeasideSt/Seaside/pull/1346
If it is, you can close the issue ;-)

**Comment by dalehenrich** [comment]
will be running tests soon, thanks!

**Comment by jbrichau** [comment]
Hey @dalehenrich. Does the solution work for this one? If yes, don't hesitate to close the issue ;-)

**Comment by dalehenrich** [comment]
@jbrichau, I got diverted by other problems. I've run the basic tests and they are passing, but I haven't got a clean seaside test run yet, other things that need addressing ... will close the bug when I find my way out of the wilderness :)
