### ISSUE TITLE
Grease adoptions for Pharo 11

### ISSUE THREAD

**Issue by astares** [SeasideSt/Grease#154]
we should adopt the baseline to work in Pharo 11 too.

For the moment it would be enough to add
```Smalltalk
spec
		for: #(#'pharo10.x' #'pharo11.x')
```
and not yet clone the packages "Grease-Pharo100-Core" into "Grease-Pharo110-Core"

**Comment by jbrichau** [comment]
Done in #155

**Comment by astares** [comment]
@jbrichau Thanks!
