### ISSUE TITLE
GRPharoPlatform>>#openDebuggerOn: is broken on Pharo 11

### ISSUE THREAD

**Issue by svenvc** [SeasideSt/Grease#158]
GRPharoPlatform>>#openDebuggerOn: is broken on Pharo 11.

A possible implementation is:
```
openDebuggerOn: anError
  (OupsDebugRequest newForException: anError) submit
```

It works and it is simple and elegant. It makes a difference between activeProcess and realActiveProcess (something I never saw before). I am not 100% sure this is totally OK though.

**Comment by jbrichau** [comment]
Hey @svenvc 
I now am using the same solution as the one you first mentioned as well on the discord channel. That is:
Replace  ```WorldState addDeferredUIMessage: ``` with: ```UIManager default defer: [ ```

It seems to work fine for me. Can you tell me what went wrong for you? I could not quite find out from the messages on discord.

**Comment by svenvc** [comment]
Yes, it is hard to quantify, that is why several opinions/experiences are needed.

But I prefer **(OupsDebugRequest newForException: anError) submit** to replace everything, but that might only work on Pharo 11.

I will ask on Discord if some of the Pharo debugger experts have an opinion on this matter.

**Comment by jbrichau** [comment]
@svenvc After playing around with your suggestion and also trying to trace the origin of the method comment, I conclude that we should try with your suggestion. I have the impression the rest of the code was a workaround for a situation that is now also handled inside the Pharo code. 

https://github.com/SeasideSt/Grease/commit/512aaeb4a0e881f78239d921905591b2e2a438de
