### ISSUE TITLE
Pharo 6 support

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Grease#17]
- `Color >> #asHTMLColor` is gone in Pharo 6 but the only senders are tests. Why do we test this method?
- `Smalltalk #removeFromShutDownList:` is gone, `#addToStartUpList:` is still there though
- `GRStringTest >> #testSubStrings` breaks but it tests ANSI behaviour
- `GRSlimeTest >> #testUsesCurlyBraceArrays` breaks but that looks like and RB bug

**Comment by jbrichau** [comment]
Saw this issue _after_ committing the fixes for Pharo 6. But just in case:

I was wondering the same thing about `Color>>asHTMLColor`, but I added the method to Grease in Pharo 6 just in case. Not a big deal to have it.

Same thought about `GRStringTests>>testSubStrings`: this is ANSI but we are developing on Pharo and Pharo leaves ANSI behind, as it seems. I added the test for `substrings:` (lowercase) and that method is now present in all dialect specific packages for Grease (or it's defined by the dialect itself). 

The rest was fixed.
