### ISSUE TITLE
Modify sends to `SmallInteger maxVal` to the current platform

### ISSUE THREAD

**Issue by eMaringolo** [SeasideSt/Grease#177]
The recently introduced `greaseByte*` methods have tests referencing `SmallInteger maxVal` and `SmallInteger minVal`, the min/max value should be asked to the current `GRPlatform`, as different dialects might resolve that using a different method selector.

This difference causes `testGreaseByte*` test cases that depend on mix/max to fail.

**Comment by jbrichau** [comment]
Hi @eMaringolo!
Since these are test-only methods, would adding the methods `SmallInteger>>maxVal` and friends as class extensions to a platform-specific (tests) package for the dialect be a feasible alternative?

**Comment by marschall** [comment]
> Hi @eMaringolo! Since these are test-only methods, would adding the methods `SmallInteger>>maxVal` and friends as class extensions to a platform-specific (tests) package for the dialect be a feasible alternative?

Wouldn't that imply / require every dialect to have a `SmallInteger` global?

**Comment by jbrichau** [comment]
> > Hi @eMaringolo! Since these are test-only methods, would adding the methods `SmallInteger>>maxVal` and friends as class extensions to a platform-specific (tests) package for the dialect be a feasible alternative?
> 
> Wouldn't that imply / require every dialect to have a `SmallInteger` global?

This is already the case since the test methods reference the `SmallInteger` global.
All platforms we currently test on (and VAST as well) have it.

**Comment by eMaringolo** [comment]
I'm closing this issue since it could be solved by adding such extensions to `SmallInteger class` in a VAST specific Grease application. Currently they're marked as expected failures anyway.
