### ISSUE TITLE
Hook into platform deprecation mechanism

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Grease#179]
At least Pharo and VASt now offer their custom deprecation mechanisms. It would be great if we could hook into this. Ideally this would allows to take advantage of platform integration features like:

- Our deprecated methods showing up as deprecated in the IDE.
- Automatic rewriting of senders.

Unfortunately at least the Pharo implementation does not seem very extensible.

```st
CompiledMethod >> isDeprecated

	^ self sendsAnySelectorOf: #(
			#deprecated:
			#deprecated:transformWith:
			#deprecated:transformWith:when:
			#deprecated:on:in:
			#deprecated:on:in:transformWith:
			#deprecated:on:in:transformWith:when:)
```

VASt seems to use `#deprecated:` and `#deprecated:in:`

**Comment by timrowledge** [comment]
Squeak uses #deprecated: *but* also rather often #flag: #deprecated in places where actually raising  Deprecation warning would cause too much annoyance.

The latter could be caught by simply adding #deprecated to the above list, if that seems appropriate
