### ISSUE TITLE
Pharo: PackageManifest

### ISSUE THREAD

**Issue by jecisc** [SeasideSt/Grease#21]
On Pharo we have now a class PackageManifest who can be subclass in all packages of the system to keep meta datas (for example for CriticBrowser banned rules).
This PackageManifest class could maybe be added in other smalltalk than Pharo to ensure the compatibility.

**Comment by krono** [comment]
This may be a feasible approach

**Comment by marschall** [comment]
Is it used for anything besides CriticBrowser? I don't think we'll switch to CriticBrowser considering the amount of custom rules we have.

**Comment by jbrichau** [comment]
It is useful for Pharo-Gemstone development though. We (at Yesplan) have the same issue in practice and include the class in Gemstone as part of our own codebase.

Should this be part of Grease? Not sure...

**Comment by marschall** [comment]
Is that a POSO (Plain Old Smalltalk Object) class or does it have any dependencies on Pharo classes?

**Comment by jbrichau** [comment]
It's a POSO yes and can indeed easily be included. But it does not mean anything in another dialect, it's just to support loading your code.
