### ISSUE TITLE
Consider adding GRPlatform >> #thisContext

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Grease#27]
Apparently `GRPlatform` on VASt has a `#thisContext` method as replacement for a missing `thisContext` variable. Gemstone/S also has not `thisContext` variable and has to change all the continuation code.

A default implementation could look like this 

```st
thisContext
  ^ thisContext sender
```

**Comment by jbrichau** [comment]
The `testThisContext` fails in Gemstone (see https://travis-ci.org/SeasideSt/Grease/jobs/272880676)

**Comment by marschall** [comment]
Yes, see #40 should we disable the test for now?

**Comment by jbrichau** [comment]
OK. No, leave in the test so we don't forget.
