### ISSUE TITLE
Consider Spec integration

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Grease#29]
For better debugger integration in Pharo we could add the following methods

For `GRSmallDictionary class`

```st
inspectorClass
	^ EyeDictionaryInspector
```

For `GRSmallOrderedSet class`

```st
inspectorClass
	^ EyeCollectionInspector
```

Maybe they should go into a `Grease-Pharo-Spec` package so we don't get undeclareds in minimal images.

**Comment by jbrichau** [comment]
Addressed for Pharo9 in #121
