### ISSUE TITLE
Consider Glamour integration

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Grease#30]
For a better debugging experience in Pharo we should consider Glamour integration for things like `GRSmallDictionary` and `GRSmallOrderedCollection`.

`Dictionary` has quite a few methods dedicated to this `#gtInspectorItemsIn:`, `#gtInspectorKeysIn:`, `#spotterForKeysFor:`, `#gtDebuggerSUnitPrint`.

Maybe they should go into a Grease-Pharo-Glamour package so we don't get undeclareds in minimal images.

**Comment by astares** [comment]
This is too old - also recent Pharo 9 reimplemented inspectors and spotter.

@jbrichau / @marschall 
I guess we should close it

**Comment by jbrichau** [comment]
@astares the title of the issue might not be applicable, but having some gtoolkit extensions for the specific Grease classes `GRSmallDictionary ` and `GRSmallOrderedCollection` is worthwhile. This is what the issue about imho.

**Comment by jbrichau** [comment]
Addressed for Pharo9 in #121
