### ISSUE TITLE
Base64 encoding for Pharo 7 (avoid Base64MimeConverter)

### ISSUE THREAD

**Issue by astares** [SeasideSt/Grease#62]
In Pharo 7 the class Base64MimeConverter should be avoided and it is better to use:

base64Decoded
base64Encoded

on String.

So GRPharoPlatform>>base64Decode: aString should be changed from 

	base64Decode: aString
		^ (Base64MimeConverter mimeDecodeToChars: aString readStream) contents

to 

	base64Decode: aString
		^ aString base64Decoded

**Comment by jbrichau** [comment]
Addressed in c88ff7edaf182be528bdaed8e62c96faa076e57e

**Comment by astares** [comment]
Thanks!
