### ISSUE TITLE
Remove build for Pharo 3

### ISSUE THREAD

**Issue by theseion** [SeasideSt/Grease#73]
We no longer support Pharo 3 with Seaside, can we also drop support for Pharo 3 in Grease? Then we could go metadataless.

**Comment by jecisc** [comment]
It would make management easier to go metadataless :)

**Comment by jecisc** [comment]
@jbrichau Any thought about this?

**Comment by jbrichau** [comment]
I guess we can start dropping it for the future and mark a specific version for Pharo3 in this repository and documentation. I don't know of any projects that would still rely on Pharo3 that use Grease (I know Tode still does... but it does not seem to use Grease) but it doesn't take too much energy to make sure these projects aren't broken needlessly.

**Comment by jecisc** [comment]
I opened this PR: https://github.com/SeasideSt/Grease/pull/80

If in the end, we do not wish to drop the compatibility it can be closed. If we drop it, it's open for review :)
