### ISSUE TITLE
Filenames with non-ascii chars are not encoded

### ISSUE THREAD

**Issue by jbrichau** [SeasideSt/Grease#8]
The GemStone primitives on GsFile are not encoding a filename with non-ascii chars. As a consequence, users must not forget to properly encode these filenames before using the primitives.

For example, executing the following in GemStone 2.4, 3.1 or 3.2 does not open the file because it does not find it.
`GRPlatform current contentsOfFile: 'fichier français à importer.txt' binary: false`

If we encode the filename, it works:
`GRPlatform current contentsOfFile: 'fichier français à importer.txt' encodeAsUTF8 binary: false`

I think this might be a GemStone issue that could be fixed if the primitives take the user locale into account. What do you think @dalehenrich ? In the meantime, we might want to abstract this into Grease with a locale that can be set in GRPlatform and that is subsequently used to encode the filename.

**Comment by dalehenrich** [comment]
This Bug44786 is fixed in 3.3 ....

**Comment by marschall** [comment]
Since 3.3 is out, 3.4 is about to ship and it's now been almost three years, do you still plan to fix this?

**Comment by jbrichau** [comment]
We have a fix for this in our own codebase but I'm not sure it can be applied in general. I'm lacking time to take this, so, no, won't fix.
