### ISSUE TITLE
GRSmallDictionary2 removeKey: is not working 

### ISSUE THREAD

**Issue by gcotelli** [SeasideSt/Grease#81]
The following code

```smalltalk
GRSmallDictionary2 new
	at: 'x' put: 'x';
	at: 'y' put: 'y';
	at: 'z' put: 'z';
	removeKey: 'z'
```
produces a subscript out of bounds. Tested in Pharo 7.

This is a simplified example, we hitted this problem in some Seaside code trying to remove some keys from the arguments of a JSObject.

**Comment by gcotelli** [comment]
Changing 
```smalltalk
GRSmallDictionary2>>removeIndex: index
	| value |
	value := table at: index + 1.
	index to: size * 2 - 2 do: [ :i | 
		table at: i put: (table at: i + 2) ].
	table at: size * 2 - 1 put: nil.
	table at: size * 2 put: nil.
	size := size - 1.
	^ value
```
makes it work.

Here's a test case showing the problem:

**Comment by gcotelli** [comment]
```smalltalk
testBugFixIssue81

	| dictionary |

	dictionary := GRSmallDictionary2 new
		at: 'x' put: 1;
		at: 'y' put: 2;
		at: 'z' put: 3;
		yourself.

	self
		assert: (dictionary removeKey: 'z') = 3;
		assert: dictionary size = 2.

	dictionary := GRSmallDictionary2 new
		at: 'x' put: 1;
		at: 'y' put: 2;
		at: 'z' put: 3;
		yourself.

	self
		assert: (dictionary removeKey: 'y') = 2;
		assert: dictionary size = 2
```

**Comment by gcotelli** [comment]
I was going to produce a PR but noticed that commiting my changes with Iceberg there was a lot of unrelated differences :(

Some caring soul can commit this changes :pray: in the right format

**Comment by gcotelli** [comment]
I produced the PR and let you decide what to do.

**Comment by jecisc** [comment]
@marianopeck Since the number of metadata full projects still out there is really low, Iceberg does not manage it. (Too much development time for too few uses)

**Comment by marianopeck** [comment]
Hi @jecisc, 
So then how are they (Grease developers) supposed to work with/for Pharo 7? They are force to migrate to Tonel?

**Comment by jecisc** [comment]
FileTree is still supported but only in metadata less mode.

To keep contributing to metadata full projects users needs to keep the same workflow than before Iceberg creation. Add a file tree repository to Monticello, export the code via Monticello in the file system then commit outside Pharo. (That was the way to use git before Pharo 6).

**Comment by marianopeck** [comment]
Thanks @jecisc for the explanation. I now understand why @marschall was considering moving to metadataless filetree. I guess at this point is not worth and would be better to move to Tonel, right?

**Comment by jecisc** [comment]
| Version | FT full | FT less | Tonel |
| ------------- | ------------- |------------- |------------- |
3 | V | With Metacello update? | X |
4 | V | V | With Metacello update + Tonel install |
5 | V | V | With Metacello update + Tonel install |
6.0 | V | V | With Metacello update + Tonel install |
6.1 | V | V | V |
7 | V | V | V |
8 | V | V | V |

**Comment by jecisc** [comment]
I begun to write a documentation on the code formats:

https://github.com/pharo-open-documentation/pharo-wiki/pull/72

**Comment by marianopeck** [comment]
Wow @jecisc  that's a really niece summary of the status! Great work! Based on that wiki page, IF we do the effort of migrating Seaside repos, I would do it for sure to Tonel. I don't care about Pharo 3 ( It was released 5 years ago) and I don't care they have to manually update Metacello + Tonel as long as that is documented and working. If you want, you can say, OK, Seaside 3.4 from now onwards will only work in Pharo > 3 and that's all. 
What I can say, is that contributing right now to Seaside is complicated, because everybody (that contributes) is likely  using Iceberg and in 6.1 or 7. This case #81 is the clearest proof of that, right?

**Comment by jecisc** [comment]
Reviewed version: [https://github.com/pharo-open-documentation/pharo-wiki/blob/master/General/ExportFormats.md](https://github.com/pharo-open-documentation/pharo-wiki/blob/master/General/ExportFormats.md)

**Comment by jbrichau** [comment]
@jecisc and @marianopeck : Moving Grease to Tonel is not possible before it's supported on Gemstone, Squeak and before there is a clear path for migrating it to repositories for other platforms (VA, VW,...). Grease is intended to be a cross-platform layer, but as far as I know Tonel is just for Pharo.

@gcotelli I'll see what I can do and comment via the PR if necessary. Thanks.

**Comment by marianopeck** [comment]
Hi @jbrichau good point about other platforms. It's not only about Pharo. I guess we want both (Seaside and Grease) to continue working in other dialects as they do now. As for VA, we are pushing for Tonel... 

Anyway, do you agree to at least update the Contributing page to explain how to contribute? I must said explicitly that these repos are Metadata full and how you would contribute that way with the different versions of Pharo, right? I am talking about this: https://github.com/SeasideSt/Seaside/blob/master/CONTRIBUTING.md

Thanks!

**Comment by jbrichau** [comment]
@marianopeck we already settled on metadataless for both repositories. Seaside already is, Grease was half-way (pharo7 package was already metadataless) and as of a few minutes ago, it's metadataless ;)

**Comment by marianopeck** [comment]
Hi @jbrichau so that means, based on above wiki, that since Pharo 4 to 8, we can contribute to Seaside using Filetree metadataless but not using Iceberg right? As @gcotelli said Iceberg does not work well enough with filetreee. Is that correct?

**Comment by jecisc** [comment]
@marianopeck metadata-less is Iceberg compatible. Only metadata full is not :) 

There is only one bug, it does not commit a full package removal, that's on my TODO list to check. (And it does not happen that often. Also, it keeps the package in the repo but the package would not be loaded)

**Comment by jbrichau** [comment]
thanks @gcotelli for fixing!

**Comment by marianopeck** [comment]
HI @jecisc thanks for you explanation. So, based on your comment "metadata-less is Iceberg compatible. Only metadata full is not :)" and based on @jbrichau " Grease was half-way (pharo7 package was already metadataless) and as of a few minutes ago, it's metadataless ;)", then the only explanation of why @gcotelli saw the problem with Iceberg is because at that time he was in the 50% of Grease that was metadata full?  That would explain everything :)

**Comment by jecisc** [comment]
That's the case I think! :)
