### ISSUE TITLE
Update baseline for Pharo 9

### ISSUE THREAD

**Issue by JanBliznicenko** [SeasideSt/Grease#98]
Loading Grease to Pharo 9 does not load Pharo-specific packages.

Probable reason is that Grease baseline has each Pharo version explicitely named in baseline and there is no entry for Pharo 9 yet.

**Comment by jbrichau** [comment]
@JanBliznicenko Sorry for the long wait. A version [1.5.1](https://github.com/SeasideSt/Grease/releases/tag/v1.5.1) has been created and you can also reference the `v1.5.x` version to get latest bugfix release at all times. 



I also added a test stage for Pharo 9.0 to the builds, but it's allowed to fail as long as Pharo 9.0 is not finalized.
